import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {address,amount,decode,unique,findings,csv,report,mergeReview} from '../static/core.mjs';
import {collect} from '../static/live.mjs';
const saved=JSON.parse(fs.readFileSync(new URL('../dist/case.json',import.meta.url)));const raw=JSON.parse(fs.readFileSync(new URL('../data/raw/logs-25929879-25929898.json',import.meta.url))).response.result;
test('rejects invalid and zero addresses',()=>{for(const v of ['abc','0x'+'0'.repeat(40),'0x'+'z'.repeat(40)])assert.throws(()=>address(v));assert.equal(address(saved.manifest.seed.toUpperCase().replace('0X','0x')),saved.manifest.seed)});
test('large uint256 remains exact',()=>{const n=(2n**200n)+123456n;assert.equal(amount(n),`${n/1000000n}.${String(n%1000000n).padStart(6,'0')}`);assert.equal(amount(1000000000n),'1000');assert.equal(amount(0n),'0');assert.equal(amount(353n),'0.000353')});
test('JavaScript decoding agrees with Python saved evidence',()=>{for(const e of saved.events){const l=raw.find(l=>l.transactionHash===e.tx&&Number(l.logIndex)===e.log_index);if(l){const decoded=decode(l);for(const k in decoded)assert.equal(decoded[k],e[k])}}});
test('removed logs and malformed hashes fail closed',()=>{assert.throws(()=>decode({...raw[0],removed:true}));assert.throws(()=>decode({...raw[0],blockHash:'0x1'}))});
test('deduplicates repeated events and rejects conflicts',()=>{const e=decode(raw[0]);assert.equal(unique([e,e]).length,1);assert.throws(()=>unique([e,{...e,units:'4'}]))});
test('candidate sequence is chronological and observed, not invented',()=>{const f=findings(saved.events,saved.manifest.seed);assert.equal(f.incoming,9);assert.equal(f.outgoing,3);assert(f.sequences.some(s=>s.amount==='353.912839'&&s.seconds===168));assert.equal(f.tiny,7)});
test('report preserves analyst notes and evidence IDs',()=>{const r=report(saved,{observations:'Check prior balance',disposition:'Further information needed'});assert(r.includes('Check prior balance'));assert(r.includes(saved.events[0].tx));assert(csv(saved.events).includes('353.912839'))});
const base=1700000000;const hash='0x'+'a'.repeat(64);const seed=saved.manifest.seed;
function mock({error=false,empty=false,wrongHash=false}={}){return async(url,opt)=>{const r=JSON.parse(opt.body);let result;if(r.method==='eth_chainId')result='0x1';if(r.method==='eth_getBlockByNumber'){const n=r.params[0]==='finalized'?100:Number(r.params[0]);result={number:'0x'+n.toString(16),timestamp:'0x'+(base+n*12).toString(16),hash}}if(r.method==='eth_call')result='0x6';if(r.method==='eth_getLogs'){if(error)return {ok:true,json:async()=>({error:{message:'rate limit'}})};result=empty?[]:[{...raw[0],blockNumber:'0x32',blockHash:wrongHash?'0x'+'b'.repeat(64):hash,topics:[raw[0].topics[0],'0x'+seed.slice(2).padStart(64,'0'),raw[0].topics[2]]}]}return {ok:true,json:async()=>({result})}}}
const params={seed,start:new Date((base+49*12)*1000).toISOString(),end:new Date((base+52*12)*1000).toISOString()};
test('live query resolves UTC boundaries, deduplicates and keeps provenance',async()=>{const c=await collect({...params,transport:mock()});assert.equal(c.manifest.from_block,49);assert.equal(c.manifest.to_block,51);assert.equal(c.events.length,1);assert(c.raw.some(r=>r.request.method==='eth_getLogs'));assert.equal(c.events[0].timestamp,new Date((base+50*12)*1000).toISOString())});
test('empty query is a valid empty case, provider failure is not',async()=>{assert.equal((await collect({...params,transport:mock({empty:true})})).events.length,0);await assert.rejects(collect({...params,transport:mock({error:true})}));await assert.rejects(collect({...params,transport:mock({wrongHash:true})}))});
test('invalid dates and future finalized windows fail',async()=>{await assert.rejects(collect({...params,start:'invalid',transport:mock()}));await assert.rejects(collect({...params,end:new Date((base+101*12)*1000).toISOString(),transport:mock()}))});
test('cancellation fails without producing partial case',async()=>{const c=new AbortController();c.abort();await assert.rejects(collect({...params,signal:c.signal,transport:mock()}))});

test('expansion preserves scope and rejects unrelated or repeated subjects',async()=>{const baseCase=await collect({...params,transport:mock()});const peer=baseCase.events[0].target;const added={...baseCase,manifest:{...baseCase.manifest,seed:peer}};const merged=mergeReview(baseCase,added);assert.equal(merged.events.length,1);assert.equal(merged.queried_addresses.length,2);assert.throws(()=>mergeReview(merged,added));assert.throws(()=>mergeReview(baseCase,{...added,end:'different'}))});
